# Generated by Django 3.1.7 on 2021-03-25 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estacioMedioambientalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.TextField(verbose_name='Identificador')),
                ('localitzacio', models.TextField(default=None, verbose_name='Localitzacio')),
                ('quarentena', models.BooleanField(verbose_name='Esta en quarentena')),
                ('dataQuarentena', models.DateTimeField(verbose_name='Inici de quarentena')),
                ('usuari', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietari')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.TextField(verbose_name='pais')),
                ('localitat', models.TextField(verbose_name='localitat')),
                ('latitud', models.FloatField(verbose_name='latitud')),
                ('longitud', models.FloatField(verbose_name='longitud')),
                ('altitud', models.FloatField(verbose_name='altitud')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.TextField(verbose_name='Tipus de sensor')),
                ('valorMaximPotable', models.FloatField(verbose_name='Valor maxim avans de que es consideri perillos')),
                ('valorMinimPotable', models.FloatField(verbose_name='Valor minim avans de que es consideri perillos')),
                ('valorMaxim', models.FloatField(verbose_name="Valor maxim que s'acceptara com a valid")),
                ('valorMinim', models.FloatField(verbose_name="Valor minim que s'acceptara com a valid")),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.TextField(verbose_name='Identificador')),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacioMedioambientalApp.client', verbose_name='Client pare')),
            ],
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now=True, verbose_name='Hora de dades')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('sensor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacioMedioambientalApp.sensor', verbose_name='Sensor')),
            ],
        ),
    ]
