# Generated by Django 3.1.7 on 2021-03-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacioMedioambientalApp', '0002_client_location_registre_sensor_sensortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='tipusSensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estacioMedioambientalApp.sensortype', verbose_name='Tipus de sensor'),
            preserve_default=False,
        ),
    ]
