# Generated by Django 3.1.7 on 2021-03-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacioMedioambientalApp', '0003_sensor_tipussensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='descripcio',
            field=models.TextField(default=None, verbose_name='Breu descripcio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensortype',
            name='unitatMesura',
            field=models.TextField(default=None, verbose_name='Unitat en la que mesura'),
            preserve_default=False,
        ),
    ]
