# Generated by Django 3.1.7 on 2021-03-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacioMedioambientalApp', '0004_auto_20210326_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='unitatMesura',
            field=models.CharField(max_length=5, verbose_name='Unitat en la que mesura'),
        ),
    ]
