# Generated by Django 3.1.7 on 2021-03-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacioMedioambientalApp', '0006_auto_20210326_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='localitzacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacioMedioambientalApp.location', verbose_name='Localitzacio'),
        ),
    ]
