# Generated by Django 3.1.7 on 2021-03-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacioMedioambientalApp', '0008_auto_20210326_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='actiu',
            field=models.BooleanField(default=True, verbose_name='Esta actiu'),
            preserve_default=False,
        ),
    ]
