# Generated by Django 3.1.7 on 2021-03-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacioMedioambientalApp', '0009_client_actiu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registre',
            name='hora',
            field=models.DateTimeField(verbose_name='Hora de dades'),
        ),
    ]
