# Generated by Django 3.1.7 on 2021-03-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacioMedioambientalApp', '0010_auto_20210328_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.TextField(default=None, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
