# Generated by Django 3.2 on 2021-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacioMedioambientalApp', '0012_auto_20210329_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='movil',
            field=models.BooleanField(default=False, verbose_name='Es movil'),
            preserve_default=False,
        ),
    ]
