# Generated by Django 3.2 on 2021-05-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacioMedioambientalApp', '0013_client_movil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='localitzacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacioMedioambientalApp.location', verbose_name='Localitzacio'),
        ),
        migrations.AlterField(
            model_name='registremovil',
            name='localitzacio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacioMedioambientalApp.location', verbose_name='Localitzacio'),
        ),
    ]
