# Generated by Django 3.2 on 2021-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacioMedioambientalApp', '0014_auto_20210509_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dataQuarentena',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inici de quarentena'),
        ),
    ]
